# Generated by Django 5.0.3 on 2024-03-31 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_holidaymeal_mealdiet_mealtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_diet',
            field=models.ManyToManyField(help_text='Hold ctrl or cmd to select more than one option', to='recipes.mealdiet'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_holiday',
            field=models.ManyToManyField(help_text='Hold ctrl or cmd to select more than one option', to='recipes.holidaymeal'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.mealtype'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='method',
            field=models.TextField(null=True),
        ),
    ]
